name: workflow_manager
description: Monday-like PM platform (scaffold, theming, protected routing)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dio: ^5.5.0
  flutter_secure_storage: ^9.2.2    # secure pe iOS/Android/macOS/Windows/Linux
  shared_preferences: ^2.3.2        # fallback pe Web (nu e truly secure)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
