version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      target: dev
    working_dir: /app
    env_file:
      - ../.env
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"

volumes:
  db_data:
